[versions]
agp = "8.13.2"
kotlin = "2.2.0"
coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
decompose = "3.4.0"
firebaseBom = "34.8.0"
windowCoreAndroid = "1.5.1"
adaptiveAndroid = "1.2.0"
material3 = "1.4.0"
junit = "5.13.4"
junit-android = "2.0.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

#JUnit5
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }

junit-android-test-core = { group = "de.mannodermaus.junit5", name = "android-test-core", version.ref = "junit-android" }
junit-android-test-runner = { group = "de.mannodermaus.junit5", name = "android-test-runner", version.ref = "junit-android" }


firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore" }

#Decompose
decompose = { group = "com.arkivanov.decompose", name = "decompose", version.ref = "decompose" }
decompose-compose = { group = "com.arkivanov.decompose", name = "extensions-compose", version.ref = "decompose" }
decompose-jetpack-component-context = { group = "com.arkivanov.decompose", name = "jetpack-component-context", version.ref = "decompose" }
decompose-coroutines = { module = "com.arkivanov.essenty:lifecycle-coroutines", version.require = "2.5.0" }

window = { module = "androidx.window:window", version.require = "1.5.1" }
androidx-window-core-android = { group = "androidx.window", name = "window-core-android", version.ref = "windowCoreAndroid" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "material3" }
material3-adaptive-layout = { group = "androidx.compose.material3.adaptive", name = "adaptive-layout", version.ref = "material3" }
material3-adaptive-navigation = { group = "androidx.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "material3" }
material3-adaptive-android = { group = "androidx.compose.material3.adaptive", name = "adaptive-android", version.ref = "adaptiveAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.require = "2.1.10-1.0.29" }
google-services = { id = "com.google.gms.google-services", version.require = "4.4.4" }
android-junit = { id = "de.mannodermaus.android-junit5", version.require = "2.0.1"}

[bundles]
firebase = ["firebase-auth", "firebase-firestore"]
junit-local = ["junit-jupiter-api", "junit-jupiter-params", "junit-jupiter-engine"]
junit-android = ["junit-android-test-core", "junit-android-test-runner"]
material3 = ["material3", "material3-adaptive", "material3-adaptive-layout", "material3-adaptive-navigation", "material3-adaptive-android"]